let pendingOwnerId=null;
let accountUser=null,saveTimer=null,saveChain=Promise.resolve();const pendingPages=new Map();
async function api(path,options={}){
 let response;
 try{response=await fetch(path,{...options,headers:{'Content-Type':'application/json',Accept:'application/json'},body:options.body===undefined?undefined:JSON.stringify(options.body)});}catch{throw Error('Unable to reach Blog Studio. Check your connection and try again.');}
 const text=await response.text();let result;
 try{result=JSON.parse(text);}catch{throw Error('Blog Studio returned an unexpected response'+(response.status>=400?' ('+response.status+')':'')+'. Refresh the page and try again. If this continues, check that the Blog Studio server is running.');}
 if(!response.ok){if(response.status===401&&accountUser){accountUser=null;$('.editor-shell').hidden=true;$('#loginScreen').hidden=false;$('#loginError').textContent='Your session expired. Sign in again; unsaved work is kept in this tab.';}throw Error(result?.error||'Request failed');}return result;
}

window.queuePageSave=page=>{if(!accountUser)return;pendingOwnerId=accountUser.id;pendingPages.set(page.id,JSON.parse(JSON.stringify(page)));$('#saved').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>flushPages().catch(()=>{}),600);};
function flushPages(){clearTimeout(saveTimer);saveChain=saveChain.catch(()=>{}).then(async()=>{for(const [id,page] of [...pendingPages]){try{await api('/api/pages/'+id,{method:'PUT',body:page});if(pendingPages.get(id)===page)pendingPages.delete(id);}catch(error){$('#saved').textContent='Not saved — retry Save draft';throw error;}}$('#saved').textContent='All changes saved';});return saveChain;}
async function signedIn(user){if(pendingPages.size&&pendingOwnerId!==user.id){await api('/api/logout',{method:'POST',body:{}});throw Error('Unsaved work belongs to the previous account. Sign in with that account to save it first.');}accountUser=user;$('#loginScreen').hidden=true;if(user.mustChangePassword){changePassword(true);return;}$('.editor-shell').hidden=false;$('#accountBtn').textContent=user.username;await flushPages();drafts=await api('/api/pages');doc=drafts[0]||{id:uid(),title:'Untitled article',blocks:[]};selected=doc.blocks[0]?.id;$('#title').value=doc.title;renderCanvas();settings();$('#saved').textContent='All changes saved';$('#draftCount').textContent=drafts.length;}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;$('#loginError').textContent='';try{const user=await api('/api/login',{method:'POST',body:{username:form.username.value,password:form.password.value}});form.password.value='';await signedIn(user);}catch(error){$('#loginError').textContent=error.message;}finally{button.disabled=false;}};
function changePassword(required=false){modal(required?'Set your new password':'Change password','<form id="passwordForm" class="account-form"><label>Current password<input name="current" type="password" autocomplete="current-password" required></label><label>New password (at least 12 characters)<input name="password" type="password" autocomplete="new-password" minlength="12" required></label><label>Confirm new password<input name="confirm" type="password" autocomplete="new-password" minlength="12" required></label><p class="form-error" role="alert"></p><button class="primary">Save password</button></form>');$('#closeModal').hidden=required;$('#modal').oncancel=e=>{if(required)e.preventDefault();};$('#modal').dataset.dismissible=String(!required);$('#passwordForm').onsubmit=async e=>{e.preventDefault();const f=e.target;try{if(f.password.value!==f.confirm.value)throw Error('Passwords do not match');await api('/api/password',{method:'POST',body:{current:f.current.value,password:f.password.value}});$('#closeModal').hidden=false;$('#modal').oncancel=null;$('#modal').close();accountUser.mustChangePassword=false;await signedIn(accountUser);toast('Password updated');}catch(error){f.querySelector('.form-error').textContent=error.message;}};}
async function pagesLibrary(){try{await flushPages();drafts=await api('/api/pages');modal('My saved pages','<p>Open a page to edit it, or reuse it as a new draft.</p>'+'<div class="saved-pages-grid">'+drafts.map(savedPageCard).join('')+'</div>'+(!drafts.length?'<p>No saved pages yet. Create your first article.</p>':'')+'<button class="secondary" id="migrateLocal">Import drafts from this browser</button>');$('#modalBody').querySelectorAll('[data-page-open]').forEach(button=>button.onclick=()=>{doc=drafts.find(d=>d.id===button.dataset.pageOpen);selected=doc.blocks[0]?.id;$('#title').value=doc.title;renderCanvas();settings();$('#modal').close();});$('#modalBody').querySelectorAll('[data-page-reuse]').forEach(button=>button.onclick=()=>{const source=drafts.find(d=>d.id===button.dataset.pageReuse);newArticle(source.blocks.map(cloneBlock),source.title+' (copy)');$('#modal').close();});$('#modalBody').querySelectorAll('[data-page-delete]').forEach(button=>button.onclick=()=>deleteSavedPage(button.dataset.pageDelete));$('#migrateLocal').onclick=async()=>{try{const old=JSON.parse(localStorage.getItem('akkodis-drafts')||'[]');if(!Array.isArray(old)||!old.length)return toast('No browser-only drafts found');for(const source of old){const copy={...source,id:uid(),blocks:source.blocks.map(cloneBlock)};await api('/api/pages/'+copy.id,{method:'PUT',body:copy});}toast('Browser drafts copied to your account');await pagesLibrary();}catch(error){toast(error.message);}};}catch(error){toast(error.message);}}
$('#pagesBtn').onclick=pagesLibrary;$('#draftNav').onclick=pagesLibrary;
$('#saveBtn').onclick=async()=>{save();try{await flushPages();toast('Page saved to your account');}catch(error){toast(error.message);}};
$('#shareTeam').onclick=async()=>{try{save();await flushPages();const users=(await api('/api/users')).filter(u=>u.id!==accountUser.id);$('.transfer-menu').open=false;modal('Share a copy with your team',users.length?'<p>The recipient gets an independent, editable copy of this page.</p><form id="shareForm" class="account-form"><label>Team member<select name="recipient">'+users.map(u=>'<option value="'+u.id+'">'+esc(u.username)+'</option>').join('')+'</select></label><button class="primary">Send copy</button><p class="form-error"></p></form>':'<p>No other accounts yet. An administrator can add team members from Account.</p>');if($('#shareForm'))$('#shareForm').onsubmit=async e=>{e.preventDefault();const f=e.target,button=f.querySelector('button');button.disabled=true;try{await api('/api/pages/'+doc.id+'/share',{method:'POST',body:{userId:f.recipient.value}});$('#modal').close();toast('Copy shared with teammate');}catch(error){f.querySelector('.form-error').textContent=error.message;button.disabled=false;}};}catch(error){toast(error.message);}};
$('#accountBtn').onclick=()=>{modal('Your account','<p>Signed in as <strong>'+esc(accountUser.username)+'</strong> · '+esc(accountUser.role)+'</p><div class="modal-actions"><button id="changePassword" class="secondary">Change password</button>'+(accountUser.role==='admin'?'<button id="manageTeam" class="secondary">Manage team</button>':'')+'<button id="logout" class="primary">Sign out</button></div>');$('#changePassword').onclick=()=>{$('#modal').close();changePassword();};if($('#manageTeam'))$('#manageTeam').onclick=manageTeam;$('#logout').onclick=async()=>{try{await flushPages();await api('/api/logout',{method:'POST',body:{}});accountUser=null;drafts=[];doc={id:uid(),title:'',blocks:[]};$('#modal').close();$('.editor-shell').hidden=true;$('#loginScreen').hidden=false;}catch(error){toast(error.message);}};};
async function manageTeam(){try{const users=await api('/api/users');$('#modal').close();modal('Team accounts','<p>Only administrators can create accounts. New users must change their temporary password.</p>'+users.map(u=>'<div class="draft-row"><strong>'+esc(u.username)+'</strong><span>'+u.role+'</span></div>').join('')+'<form id="createUser" class="account-form"><label>Username<input name="username" pattern="[a-z0-9._-]{3,40}" required></label><label>Role<select name="role"><option value="editor">Editor</option><option value="admin">Administrator</option></select></label><button class="primary">Create account</button><p class="form-error"></p></form>');$('#createUser').onsubmit=async e=>{e.preventDefault();const f=e.target;try{const result=await api('/api/users',{method:'POST',body:{username:f.username.value,role:f.role.value}});$('#modalBody').innerHTML='<p>Account created. Give these temporary credentials to your teammate.</p><p>Username: <strong>'+esc(result.username)+'</strong></p><label class="setting-field">Temporary password<input readonly value="'+esc(result.temporaryPassword)+'"></label><p>This password is shown only now. The user must change it on first sign-in.</p>';}catch(error){f.querySelector('.form-error').textContent=error.message;}};}catch(error){toast(error.message);}}
window.addEventListener('beforeunload',e=>{if(pendingPages.size){e.preventDefault();e.returnValue='';}});
api('/api/me').then(signedIn).catch(error=>{if(accountUser)$('#loginError').textContent=error.message;});

function deleteSavedPage(id){
 const page=drafts.find(d=>d.id===id);if(!page)return;
 modal('Delete saved page?','<p>Delete <strong>'+esc(page.title)+'</strong>? This cannot be undone. Copies shared with teammates will remain.</p><div class="modal-actions"><button class="secondary" id="cancelPageDelete">Cancel</button><button class="primary" id="confirmPageDelete">Delete page</button></div><p class="form-error" id="deletePageError" role="alert"></p>');
 $('#cancelPageDelete').onclick=pagesLibrary;
 $('#confirmPageDelete').onclick=async()=>{const button=$('#confirmPageDelete');button.disabled=true;try{
  await flushPages();await api('/api/pages/'+id,{method:'DELETE',body:{}});pendingPages.delete(id);drafts=drafts.filter(d=>d.id!==id);
  if(doc.id===id){doc={id:uid(),title:'Untitled article',blocks:[]};selected=undefined;$('#title').value=doc.title;renderCanvas();settings();$('#saved').textContent='New page';}
  $('#draftCount').textContent=drafts.length;await pagesLibrary();toast('Page deleted');
 }catch(error){$('#deletePageError').textContent=error.message;button.disabled=false;}};
}

function savedPageCard(page){
 const icon=(path)=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+path+'</svg>';
 const actions=[['open','Open page','<path d="M14 3h7v7M21 3l-10 10M10 5H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5"/>'],['reuse','Reuse as new page','<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>'],['delete','Delete page','<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>']];
 return '<article class="saved-page-card"><div class="saved-page-info"><strong>'+esc(page.title||'Untitled article')+'</strong><small>'+esc(new Date(page.updated).toLocaleDateString())+' · '+page.blocks.length+' sections</small>'+(page.sharedBy?'<small>Shared by '+esc(page.sharedBy)+'</small>':'')+'</div><div class="saved-page-actions">'+actions.map(([action,label,path])=>'<button class="page-icon-button" data-page-'+action+'="'+page.id+'" aria-label="'+label+': '+esc(page.title)+'" title="'+label+'">'+icon(path)+'</button>').join('')+'</div></article>';
}
