const brandPalette=[{"name":"neutrals-0","value":"#FFFFFF"},{"name":"neutrals-100","value":"#F8F8F9"},{"name":"neutrals-200","value":"#EBEEEF"},{"name":"neutrals-300","value":"#D6D7D8"},{"name":"neutrals-400","value":"#BEC3C5"},{"name":"neutrals-500","value":"#6B7476"},{"name":"neutrals-600","value":"#464C51"},{"name":"neutrals-700","value":"#37393B"},{"name":"neutrals-800","value":"#11151B"},{"name":"accent-100","value":"#FFFAED"},{"name":"accent-200","value":"#FFEAB2"},{"name":"accent-300","value":"#FFE287"},{"name":"accent-400","value":"#FFC743"},{"name":"accent-500","value":"#FFB81C"},{"name":"accent-600","value":"#F29E13"},{"name":"accent-700","value":"#D48208"},{"name":"action-100","value":"#FFFAED"},{"name":"action-200","value":"#FFEAB2"},{"name":"action-300","value":"#FFE287"},{"name":"action-400","value":"#FFC743"},{"name":"action-500","value":"#FFB81C"},{"name":"action-600","value":"#F29E13"},{"name":"action-700","value":"#D48208"},{"name":"primary-100","value":"#F0F3F6"},{"name":"primary-200","value":"#768FAE"},{"name":"primary-300","value":"#003E66"},{"name":"primary-400","value":"#082F48"},{"name":"primary-500","value":"#001F33"},{"name":"primary-600","value":"#000F18"},{"name":"primary-700","value":"#00090F"},{"name":"secondary-100","value":"#EDFFFF"},{"name":"secondary-200","value":"#D2FBFB"},{"name":"secondary-300","value":"#B6FFFF"},{"name":"secondary-400","value":"#00FFFF"},{"name":"secondary-500","value":"#00A0C9"},{"name":"secondary-600","value":"#007997"},{"name":"secondary-700","value":"#005165"},{"name":"tertiary-100","value":"#2EFFFE"},{"name":"tertiary-200","value":"#51D4E5"},{"name":"tertiary-300","value":"#00A0C9"},{"name":"tertiary-400","value":"#013E65"},{"name":"tertiary-500","value":"#996E11"},{"name":"tertiary-600","value":"#FEB81B"},{"name":"success-100","value":"#DCF5D6"},{"name":"success-200","value":"#96E283"},{"name":"success-400","value":"#73D85A"},{"name":"success-600","value":"#33841F"},{"name":"alert-100","value":"#FFF6C8"},{"name":"alert-200","value":"#FFEA7A"},{"name":"alert-400","value":"#FEDA49"},{"name":"alert-600","value":"#E1B400"},{"name":"error-100","value":"#F7D3D0"},{"name":"error-200","value":"#F0A6A1"},{"name":"error-400","value":"#E87A71"},{"name":"error-600","value":"#E04D42"}];
const approvedColors=new Set(brandPalette.map(c=>c.value));
const $=s=>document.querySelector(s);
const types={heading:{name:'Heading',icon:'H₂',fields:['text'],text:'A new perspective',level:'h2'},text:{name:'Text',icon:'¶',fields:['text'],text:'Share your story here. Select this block and use the settings to bring your ideas to life.'},columns:{name:'Two columns',icon:'◫',fields:['leftTitle','left','rightTitle','right'],leftTitle:'People at the heart',left:'Great ideas start with curious people. Bring together expertise and new perspectives to solve meaningful challenges.',rightTitle:'Technology with purpose',right:'Connect digital innovation with real-world experience to create lasting impact.'},image:{name:'Image',icon:'▧',fields:['url','alt','caption'],url:'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1400&q=85',alt:'Engineer working in an industrial facility',caption:'Engineering a smarter, more connected future.'},quote:{name:'Quote',icon:'“',fields:['text','author'],text:'Progress happens when we bring people and technology together.',author:'Akkodis perspective'},list:{name:'Bullet list',icon:'☷',fields:['text'],text:'Put people at the center\nThink beyond the expected\nCreate a lasting impact'},callout:{name:'Callout',icon:'✧',fields:['text'],text:'The big idea: small improvements today can create extraordinary possibilities tomorrow.'},button:{name:'Button',icon:'▭',fields:['text','url'],text:'Discover more',url:'https://www.akkodis.com'},divider:{name:'Divider',icon:'―',fields:[]}};
const uid=()=>crypto.randomUUID();
const make=(type,values={})=>({...types[type],type,id:uid(),...values,...(type==='columns'?{columns:[[],[]]}:{})});
const initial=()=>[make('heading',{text:'The future of smarter manufacturing',level:'h1'}),make('text',{text:'Where human ingenuity meets technology. Discover how a connected approach is shaping the next era of manufacturing.',intro:true}),make('image'),make('heading',{text:'A smarter approach. A greater impact.'}),make('columns')];
let drafts=[];try{drafts=JSON.parse(localStorage.getItem('akkodis-drafts')||'[]');if(!Array.isArray(drafts))drafts=[];}catch{}
let doc=drafts[0]||{id:uid(),title:'The future of smarter manufacturing',blocks:initial()},selected=doc.blocks[doc.blocks.length-1]?.id,mobile=false,activeField=null;
function columnChildren(b){
 if(!b.columns)b.columns=[['leftTitle','left'],['rightTitle','right']].map(([title,body])=>[...(b[title]?[make('heading',{text:b[title],level:'h3'})]:[]),...(b[body]?[make('text',{text:b[body]})]:[])]);
 return b.columns;
}
function allBlocks(list=doc.blocks){return list.flatMap(b=>[b,...(b.type==='columns'?columnChildren(b).flatMap(c=>allBlocks(c)):[])]);}
function blockList(id,list=doc.blocks){if(list.some(b=>b.id===id))return list;for(const b of list){if(b.type==='columns')for(const col of columnChildren(b)){const found=blockList(id,col);if(found)return found;}}return null;}
function cloneBlock(b){const copy={...b,id:uid()};if(b.type==='columns')copy.columns=columnChildren(b).map(col=>col.map(cloneBlock));return copy;}
function canvasBlock(b){return '<div class="article-block '+(b.id===selected?'selected':'')+'" data-id="'+b.id+'" tabindex="0" aria-label="Edit '+types[b.type].name+'">'+(b.id===selected?blockToolbar(b):'')+content(b,false,true)+'</div>';}
function columnContent(b,editing=false){return '<div class="columns" style="display:flex;flex-wrap:wrap;gap:28px;">'+columnChildren(b).map((col,i)=>'<div class="column-content" style="flex:1 1 250px;min-width:0;">'+(editing?'<div class="column-label">Column '+(i+1)+'</div>':'')+col.map(child=>editing?canvasBlock(child):content(child)).join('')+(editing?'<button class="column-add" data-column-parent="'+b.id+'" data-column-index="'+i+'">＋ Add element</button>':'')+'</div>').join('')+'</div>';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeUrl(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?esc(u.href):'';}catch{return '';}}
const para=s=>esc(s).replace(/\n/g,'<br>');
const articleStyle='box-sizing:border-box;width:100%;max-width:822px;margin:0 auto;padding:8px;font-family:Roboto,Arial,Helvetica,sans-serif;font-size:16px;line-height:28px;color:#37393B;background:#FFFFFF;overflow-wrap:anywhere;';
function calloutStyle(b){
 const color=(value,fallback)=>approvedColors.has(String(value||'').toUpperCase())?String(value).toUpperCase():fallback;
 const number=(value,fallback,min,max)=>Math.max(min,Math.min(max,Number.isFinite(Number(value))&&value!==undefined&&value!==''?Number(value):fallback));
 return {background:color(b.background,'#F8F8F9'),color:color(b.textColor,'#37393B'),fontSize:number(b.fontSize,16,10,64),padding:number(b.padding,20,0,80),radius:number(b.radius,0,0,48),align:['left','center','right','justify'].includes(b.align)?b.align:'left'};
}
function calloutHtml(b){const v=calloutStyle(b);return '<div style="background:'+v.background+';padding:'+v.padding+'px;border-radius:'+v.radius+'px;text-align:'+v.align+';">'+String(b.text||'').split(/\n\s*\n/).map((part,i)=>'<p style="font-family:Roboto,Arial,sans-serif;font-size:'+v.fontSize+'px;line-height:1.5;color:'+v.color+';margin:'+(i?'16px 0 0':'0')+';">'+para(part)+'</p>').join('\n')+'</div>';}
function content(b,exporting=false,editing=false){
 const p='font-family:Roboto,Arial,Helvetica,sans-serif;font-size:16px;line-height:28px;color:#37393B;margin:0 0 16px;';
 const heading='font-family:Roboto,Arial,Helvetica,sans-serif;color:#11151B;line-height:1.4;font-weight:700;';
 switch(b.type){
 case 'heading':{const h=/^h[1-6]$/.test(b.level)?b.level:'h2';const size={h1:28,h2:18,h3:36,h4:32,h5:15,h6:14}[h];const brandHeading=(h==='h3'||h==='h4')?'font-family:TiemposRegular,Georgia,serif;line-height:'+(h==='h3'?40:35)+'px;':'';return '<'+h+' style="'+heading+'font-size:'+size+'px;margin:0 0 12px;'+brandHeading+'">'+esc(b.text)+'</'+h+'>';}
 case 'text':return b.text.split(/\n\s*\n/).map((part,i)=>'<p style="'+p+''+'">'+para(part)+'</p>').join('');
 case 'image':return '<figure style="margin:0 0 16px"><img class="hero-image" src="'+safeUrl(b.url)+'" alt="'+esc(b.alt)+'" style="width:100%;height:auto;display:block;border-radius:0;">'+(b.caption?'<figcaption style="font:12px/1.5 Roboto,Arial,sans-serif;color:#6B7476;margin-top:8px;text-align:center;">'+esc(b.caption)+'</figcaption>':'')+'</figure>';
 case 'columns':return columnContent(b,editing);
 case 'quote':return '<blockquote style="border-left:3px solid #BEC3C5;padding:16px 20px;margin:0;background:#F8F8F9;font:18px/1.5 Roboto,Arial,sans-serif;color:#37393B;">“'+para(b.text)+'”<small style="display:block;font:14px/1.5 Roboto,Arial,sans-serif;margin-top:12px;color:#6B7476;">'+esc(b.author)+'</small></blockquote>';
 case 'list':return '<ul style="'+p+'list-style-type:square;padding:0 0 0 24px;">'+b.text.split('\n').filter(Boolean).map((t,i)=>'<li style="color:#FFB81C;padding:0;'+(i?'margin-top:12px;':'')+'"><span style="color:#37393B;">'+esc(t)+'</span></li>').join('')+'</ul>';
 case 'callout':return calloutHtml(b);
 case 'button':return '<a href="'+safeUrl(b.url)+'" style="display:inline-block;background:#001F33;color:white;text-decoration:none;padding:12px 20px;font:14px/1.5 Roboto,Arial,sans-serif;">'+esc(b.text)+' →</a>';
 default:return '<hr style="margin:0;border:0;border-top:1px solid #D6D7D8;">';
 }
}
// Sitecore supplies article typography; export only content and essential custom layouts.
function exportBlock(b){
 const text=value=>para(value).replace(/\u00a0/g,'&nbsp;');
 const paragraphs=value=>String(value??'').split(/\n\s*\n/).map(part=>'<p>'+text(part)+'</p>').join('\n');
 switch(b.type){
 case 'heading':{const h=/^h[1-6]$/.test(b.level)?b.level:'h2';return '<'+h+'><strong>'+text(b.text)+'</strong></'+h+'>';}
 case 'text':return paragraphs(b.text);
 case 'image':return '<img src="'+safeUrl(b.url)+'" alt="'+esc(b.alt)+'" width="100%" height="auto">'+(b.caption?'\n<p><em>'+text(b.caption)+'</em></p>':'');
 case 'list':return '<ul>\n'+b.text.split('\n').filter(Boolean).map(t=>'    <li>'+text(t)+'</li>').join('\n')+'\n</ul>';
 case 'quote':return '<div><img alt="" src="https://www.akkodis.com/-/media/project/akkodis/akkodis/images/article-media/tm-article-7-ai-advances-herald-coding-changes/formatquote">&nbsp;</div>\n<p class="quotesText"><em>'+text(b.text)+'</em></p>'+(b.author?'\n<p><em>'+text(b.author)+'</em></p>':'');
 case 'columns':return '<div style="display:flex;flex-wrap:wrap;gap:28px;">\n'+columnChildren(b).map(col=>'  <div style="flex:1 1 250px;min-width:0;">\n'+col.map(exportBlock).join('\n')+'\n  </div>').join('\n')+'\n</div>';
 case 'callout':return calloutHtml(b);
 case 'button':return '<p><a href="'+safeUrl(b.url)+'" style="display:inline-block;background:#001F33;color:#FFFFFF;text-decoration:none;padding:12px 20px;">'+text(b.text)+'</a></p>';
 default:return '<hr>';
 }
}
function html(){return doc.blocks.map(exportBlock).join('\n');}
function previewHtml(){return '<article lang="en" style="'+articleStyle+'">'+doc.blocks.map(b=>content(b)).join('\n')+'</article>';}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function save(){doc.updated=new Date().toISOString();drafts=[doc,...drafts.filter(d=>d.id!==doc.id)];try{localStorage.setItem('akkodis-drafts',JSON.stringify(drafts));$('#saved').textContent='All changes saved';}catch{$('#saved').textContent='Storage full — export to save';}$('#draftCount').textContent=drafts.length;}
const toolIcons={edit:'<path d="m3 11 8-8 3 3-8 8-4 1zM9 5l3 3"/>',copy:'<rect x="5" y="5" width="9" height="9" rx="1"/><path d="M10 3H3v7"/>',delete:'<path d="M2 4h12M6 4V2h4v2M4 4l1 10h6l1-10M7 7v4M9 7v4"/>'};
function blockToolbar(b){return '<div class="block-tools">'+['edit','copy','delete'].map(action=>'<button data-block-action="'+action+'" aria-label="'+action+' selected section" title="'+action[0].toUpperCase()+action.slice(1)+' section"><svg viewBox="0 0 16 16" aria-hidden="true">'+toolIcons[action]+'</svg></button>').join('')+'</div><div class="block-move"><button data-block-action="up" aria-label="Move section up" '+(blockList(b.id)?.[0]?.id===b.id?'disabled':'')+'>↑</button><button data-block-action="down" aria-label="Move section down" '+(blockList(b.id)?.at(-1)?.id===b.id?'disabled':'')+'>↓</button></div>';}
function renderCanvas(){
 $('#canvas').innerHTML=doc.blocks.map(canvasBlock).join('');
 $('#canvas').querySelectorAll('[data-id]').forEach(el=>{
 el.onclick=e=>{if(e.target.closest('[data-block-action],.column-add')||e.target.closest('[data-id]')!==el)return;e.preventDefault();selected=el.dataset.id;renderCanvas();settings();};
 el.ondblclick=e=>{if(e.target.closest('[data-block-action],.column-add')||e.target.closest('[data-id]')!==el)return;selected=el.dataset.id;renderCanvas();settings();showPanel('edit');};
 el.onkeydown=e=>{if(e.target!==el)return;if(e.key==='Enter'){selected=el.dataset.id;renderCanvas();settings();showPanel('edit');}};
 });
 $('#canvas').querySelectorAll('[data-block-action]').forEach(el=>el.onclick=e=>{e.preventDefault();e.stopPropagation();const action=el.dataset.blockAction;if(action==='edit'){settings();showPanel('edit');$('#settings textarea, #settings input, #settings select')?.focus();}else if(action==='copy'){$('#duplicate')?.click();}else if(action==='delete'){$('#remove')?.click();}else move(action==='up'?-1:1);});
 $('#canvas').querySelectorAll('.column-add').forEach(button=>button.onclick=e=>{e.stopPropagation();const parent=allBlocks().find(b=>b.id===button.dataset.columnParent),index=Number(button.dataset.columnIndex);modal('Add element to column '+(index+1),'<div class="block-grid">'+Object.keys(types).filter(type=>type!=='columns').map(type=>'<button class="block-tile" data-column-type="'+type+'"><span>'+types[type].icon+'</span>'+types[type].name+'</button>').join('')+'</div>');$('#modalBody').querySelectorAll('[data-column-type]').forEach(choice=>choice.onclick=()=>{const child=make(choice.dataset.columnType);columnChildren(parent)[index].push(child);selected=child.id;update();$('#modal').close();showPanel('edit');});});
 const words=allBlocks().filter(b=>b.type!=='columns').map(b=>types[b.type].fields.filter(k=>!['url','alt'].includes(k)).map(k=>b[k]||'').join(' ')).join(' ').trim().split(/\s+/).filter(Boolean).length;
 $('#wordCount').textContent=doc.blocks.length+' sections · '+words+' words';renderOutline();
}
let draggedOutlineId=null;
function renderOutline(){
  const outline=$('#outline');
  outline.innerHTML='<p class="outline-help">Drag the handle to reorder blocks.</p>'+doc.blocks.map((b,i)=>`<div class="outline-row ${b.id===selected?'is-selected':''}" data-outline-row="${b.id}"><div class="outline-main"><button class="outline-handle" draggable="true" data-drag="${b.id}" aria-label="Move ${types[b.type].name}, block ${i+1}. Drag or use arrow keys." title="Drag to reorder, or use ↑ and ↓">⠿</button><button class="outline-select" data-outline="${b.id}" aria-pressed="${b.id===selected}"><span class="layer-icon">${b.type==='heading'?(b.level||'h2').toUpperCase():types[b.type].icon}</span><span class="layer-label">${types[b.type].name}</span></button></div><div class="outline-actions"><button data-copy="${b.id}" aria-label="Copy block ${i+1}">⧉ Copy</button><button data-delete="${b.id}" aria-label="Delete block ${i+1}">⌫ Delete</button></div></div>`).join('')+(doc.blocks.length?'':'<p class="outline-help">No blocks yet. Add one from Content blocks.</p>');
  doc.blocks.filter(b=>b.type==='columns').forEach(parent=>{const row=outline.querySelector('[data-outline-row="'+parent.id+'"]');const nested=document.createElement('div');nested.className='column-outline';nested.innerHTML=columnChildren(parent).map((col,i)=>'<div class="column-outline-label">Column '+(i+1)+'</div>'+col.map(child=>'<button class="outline-select" data-outline="'+child.id+'" aria-pressed="'+(child.id===selected)+'">'+types[child.type].icon+' '+types[child.type].name+'</button>').join('')+(col.length?'':'<small>Empty — add an element on the canvas</small>')).join('');row.append(nested);});
  outline.querySelectorAll('[data-outline]').forEach(el=>el.onclick=()=>{selected=el.dataset.outline;renderCanvas();settings();$('#canvas').querySelector(`[data-id="${selected}"]`).scrollIntoView({behavior:'smooth',block:'center'});});
  outline.querySelectorAll('[data-copy]').forEach(el=>el.onclick=()=>{
    const index=doc.blocks.findIndex(b=>b.id===el.dataset.copy);
    if(index<0)return;
    const copy=cloneBlock(doc.blocks[index]);
    doc.blocks.splice(index+1,0,copy);selected=copy.id;update();
    outline.querySelector(`[data-copy="${copy.id}"]`).focus();toast('Block copied');
  });
  outline.querySelectorAll('[data-delete]').forEach(el=>el.onclick=()=>{
    const index=doc.blocks.findIndex(b=>b.id===el.dataset.delete);
    if(index<0)return;
    const removed=doc.blocks.splice(index,1)[0];
    if(selected===removed.id||(removed.type==='columns'&&allBlocks([removed]).some(b=>b.id===selected)))selected=doc.blocks[Math.min(index,doc.blocks.length-1)]?.id;
    update();
    const next=doc.blocks[Math.min(index,doc.blocks.length-1)];
    (next?outline.querySelector(`[data-outline="${next.id}"]`):$('#blocksTab')).focus();toast('Block deleted');
  });
  const clearDrop=()=>outline.querySelectorAll('.drop-before,.drop-after').forEach(row=>row.classList.remove('drop-before','drop-after'));
  outline.querySelectorAll('[data-drag]').forEach(handle=>{
    handle.ondragstart=e=>{draggedOutlineId=handle.dataset.drag;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggedOutlineId);handle.closest('.outline-row').classList.add('dragging');};
    handle.ondragend=()=>{draggedOutlineId=null;clearDrop();outline.querySelectorAll('.dragging').forEach(row=>row.classList.remove('dragging'));};
    handle.onkeydown=e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();selected=handle.dataset.drag;move(e.key==='ArrowUp'?-1:1);outline.querySelector(`[data-drag="${selected}"]`).focus();};
  });
  outline.querySelectorAll('[data-outline-row]').forEach(row=>{
    row.ondragover=e=>{if(!draggedOutlineId)return;e.preventDefault();e.dataTransfer.dropEffect='move';clearDrop();if(row.dataset.outlineRow===draggedOutlineId)return;const rect=row.getBoundingClientRect();row.classList.add(e.clientY<rect.top+rect.height/2?'drop-before':'drop-after');};
    row.ondrop=e=>{
      if(!draggedOutlineId)return;e.preventDefault();
      const source=draggedOutlineId,target=row.dataset.outlineRow;
      const rect=row.getBoundingClientRect(),after=e.clientY>=rect.top+rect.height/2;
      draggedOutlineId=null;clearDrop();
      if(source===target)return;
      const from=doc.blocks.findIndex(b=>b.id===source);
      if(from<0||!doc.blocks.some(b=>b.id===target))return;
      const block=doc.blocks.splice(from,1)[0];
      const to=doc.blocks.findIndex(b=>b.id===target)+(after?1:0);
      doc.blocks.splice(to,0,block);selected=source;update();
      outline.querySelector(`[data-drag="${source}"]`).focus();toast('Block moved');
    };
  });
}
const labels={text:'Content',leftTitle:'Left heading',left:'Left column',rightTitle:'Right heading',right:'Right column',url:'Image URL',alt:'Image description (alt text)',caption:'Caption',author:'Attribution'};
function calloutControls(b){const v=calloutStyle(b);return '<div class="setting-section">CALLOUT APPEARANCE</div>'+[['background','Background color',v.background],['textColor','Text color',v.color]].map(([key,label,value])=>'<label class="setting-field">'+label+'<span class="brand-color-preview" style="background:'+value+'"></span><select data-style="'+key+'">'+brandPalette.filter((entry,index,list)=>list.findIndex(c=>c.value===entry.value)===index).map(entry=>'<option value="'+entry.value+'" '+(entry.value===value?'selected':'')+'>'+entry.name+' · '+entry.value+'</option>').join('')+'</select></label>').join('')+[['fontSize','Font size (px)',v.fontSize,10,64],['padding','Inner spacing (px)',v.padding,0,80],['radius','Corner rounding (px)',v.radius,0,48]].map(([key,label,value,min,max])=>'<label class="setting-field">'+label+'<input type="number" data-style="'+key+'" value="'+value+'" min="'+min+'" max="'+max+'" step="1"></label>').join('')+'<label class="setting-field">Text alignment<select data-style="align">'+['left','center','right','justify'].map(value=>'<option value="'+value+'" '+(value===v.align?'selected':'')+'>'+value[0].toUpperCase()+value.slice(1)+'</option>').join('')+'</select></label><button type="button" class="secondary" id="resetCallout">Reset appearance</button>';}
function settings(){const b=allBlocks().find(b=>b.id===selected);if(!b){$('#settings').innerHTML='<p class="setting-help">Add a content block to begin your story.</p>';return;}$('#settings').innerHTML=`<div class="selected-type">${types[b.type].icon} &nbsp; ${types[b.type].name}</div>${b.type==='heading'?`<label class="setting-field">Heading level<select id="level">${[1,2,3,4,5,6].map(n=>`<option value="h${n}" ${(b.level||'h2')==='h'+n?'selected':''}>H${n} · ${n===1?'Article title':n===2?'Section heading':'Subheading level '+n}</option>`).join('')}</select></label>`:''}${b.type==='columns'?'<p class="setting-help">Use Add element inside either column. Select an element to edit, copy, remove, or move it within that column.</p>':''}${(b.type==='columns'?[]:types[b.type].fields).map(k=>`<label class="setting-field">${k==='url'&&b.type==='button'?'Link URL':labels[k]}${['text','left','right'].includes(k)?`<textarea data-field="${k}">${esc(b[k])}</textarea>`:`<input data-field="${k}" value="${esc(b[k])}">`}</label>`).join('')}${b.type==='callout'?calloutControls(b):''}<div class="setting-section">BLOCK ACTIONS</div><div class="actions-row"><button id="up" title="Move up">↑</button><button id="down" title="Move down">↓</button><button id="duplicate">Duplicate</button></div><button class="delete-button" id="remove">⌫ &nbsp; Remove block</button><p class="setting-help">Changes appear instantly in your canvas. Your brand styling is already taken care of.</p>`;$('#settings').querySelectorAll('[data-field]').forEach(el=>{el.onfocus=()=>activeField=el;el.oninput=()=>{b[el.dataset.field]=el.value;save();renderCanvas();};});$('#settings').querySelectorAll('[data-style]').forEach(input=>{input.oninput=()=>{if(input.type==='number'&&!input.validity.valid)return;b[input.dataset.style]=input.type==='number'?Number(input.value):input.value;save();renderCanvas();};});if($('#resetCallout'))$('#resetCallout').onclick=()=>{for(const key of ['background','textColor','fontSize','padding','radius','align'])delete b[key];update();};if($('#level'))$('#level').onchange=e=>{b.level=e.target.value;save();renderCanvas();};$('#up').onclick=()=>move(-1);$('#down').onclick=()=>move(1);$('#duplicate').onclick=()=>{const list=blockList(b.id);const copy=cloneBlock(b);list.splice(list.indexOf(b)+1,0,copy);selected=copy.id;update();};$('#remove').onclick=()=>{const list=blockList(b.id),i=list.indexOf(b);list.splice(i,1);selected=list[Math.min(i,list.length-1)]?.id;update();};}
function move(delta){const list=blockList(selected);if(!list)return;const i=list.findIndex(b=>b.id===selected),j=i+delta;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];update();}
function update(){allBlocks().filter(b=>b.type==='callout').forEach(b=>{const v=calloutStyle(b);b.background=v.background;b.textColor=v.color;});save();renderCanvas();settings();}
function library(query=''){for(const [selector,keys] of [['#essentialBlocks',['heading','text','columns','image','quote','list']],['#specialBlocks',['callout','button','divider']]]){$(selector).innerHTML=keys.filter(t=>types[t].name.toLowerCase().includes(query.toLowerCase())).map(t=>`<button class="block-tile" data-type="${t}"><span>${types[t].icon}</span>${types[t].name}</button>`).join('');$(selector).querySelectorAll('button').forEach(el=>el.onclick=()=>{const b=make(el.dataset.type);const i=doc.blocks.findIndex(x=>x.id===selected);doc.blocks.splice(i<0?doc.blocks.length:i+1,0,b);selected=b.id;update();showPanel('layers');$('#canvas').querySelector(`[data-id="${selected}"]`).scrollIntoView({behavior:'smooth',block:'center'});toast(`${types[b.type].name} added`);});}}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal();}
$('#closeModal').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
$('#title').value=doc.title;$('#title').oninput=e=>{doc.title=e.target.value;save();};$('#search').oninput=e=>library(e.target.value);
$('#desktopBtn').onclick=()=>device(false);$('#mobileBtn').onclick=()=>device(true);function device(value){mobile=value;$('#canvas').classList.toggle('mobile',value);$('#mobileBtn').classList.toggle('selected',value);$('#desktopBtn').classList.toggle('selected',!value);}
function showPanel(panel){
 $('#layersPanel').hidden=panel!=='layers';$('#blockLibrary').hidden=panel!=='library';$('#editPanel').hidden=panel!=='edit';
 $('#outlineTab').classList.toggle('selected',panel!=='edit');$('#stylesTab').classList.toggle('selected',panel==='edit');
 $('#outlineTab').setAttribute('aria-selected',String(panel!=='edit'));$('#stylesTab').setAttribute('aria-selected',String(panel==='edit'));
}
$('#blocksTab').onclick=()=>{showPanel('library');$('#search').focus();};
$('#outlineTab').onclick=()=>showPanel('layers');$('#backLayers').onclick=()=>showPanel('layers');
$('#stylesTab').onclick=()=>{settings();showPanel('edit');};
$('#saveBtn').onclick=()=>{save();toast($('#saved').textContent==='All changes saved'?'Draft saved in this browser':$('#saved').textContent);};
$('#addBlockBtn').onclick=()=>$('#blocksTab').click();
$('#exportBtn').onclick=()=>{modal('Ready for Sitecore',`<p>Copy this content into your Sitecore HTML field. Headings, paragraphs, lists, and quotes inherit your website styling. Custom layouts keep essential styles. Check the final appearance in Sitecore preview.</p><textarea readonly aria-label="Exported HTML">${esc(html())}</textarea><div class="modal-actions"><button class="secondary" id="download">↓ Download HTML</button><button class="primary" id="copy">Copy HTML</button></div>`);$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(html());toast('HTML copied to clipboard');$('#copy').textContent='✓ Copied';}catch{$('#modalBody textarea').select();toast('Press Ctrl+C to copy the selected HTML');}};$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([html()],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=(doc.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'article')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};};
$('#previewBtn').onclick=()=>{modal('Article preview','<iframe title="Article preview" sandbox=""></iframe>');$('#modalBody iframe').srcdoc=`<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700&display=swap"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="padding:0;margin:0;background:#FFFFFF">${previewHtml()}</body></html>`;};
function newArticle(blocks=[],title='Untitled article'){save();doc={id:uid(),title,blocks};selected=blocks[0]?.id;$('#title').value=title;update();toast('New draft created');}
$('#newBtn').onclick=()=>newArticle([make('heading',{text:'Your story starts here',level:'h1'}),make('text')]);
$('#draftNav').onclick=()=>{modal('My drafts',drafts.map(d=>`<div class="draft-row"><div><strong>${esc(d.title||'Untitled article')}</strong><small>${d.blocks.length} blocks · ${new Date(d.updated||Date.now()).toLocaleDateString()}</small></div><button class="secondary" data-open="${d.id}">Open draft →</button></div>`).join(''));$('#modalBody').querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>{doc=drafts.find(d=>d.id===el.dataset.open);selected=doc.blocks[0]?.id;$('#title').value=doc.title;update();$('#modal').close();});};
$('#templateNav').onclick=()=>{modal('A head start for every story',`<p>Choose a starting point. Your current article stays saved in My drafts.</p><button class="template-card" data-template="feature"><strong>◫ &nbsp; Editorial feature</strong><small>A title, introduction, hero image, and two-column story.</small></button><button class="template-card" data-template="perspective"><strong>“ &nbsp; Expert perspective</strong><small>Give your experts a voice with a statement and featured quote.</small></button><button class="template-card" data-template="blank"><strong>＋ &nbsp; A fresh page</strong><small>Start with a heading and make it your own.</small></button>`);$('#modalBody').querySelectorAll('[data-template]').forEach(el=>el.onclick=()=>{const t=el.dataset.template;newArticle(t==='feature'?initial():t==='perspective'?[make('heading',{text:'An expert perspective',level:'h1'}),make('text'),make('quote'),make('heading'),make('text')]:[make('heading',{text:'Your next great story',level:'h1'})],t==='feature'?'The future of smarter manufacturing':t==='perspective'?'An expert perspective':'Untitled article');$('#modal').close();});};
function guide(){modal('From idea to article, in four steps',`<ol><li><strong>Start your story.</strong> Choose a template or create a new article.</li><li><strong>Build with blocks.</strong> Click any content block in the library to add it after your selected block.</li><li><strong>Make it yours.</strong> Select a block in the canvas and edit its content in the Edit block panel. Use the floating pencil button or Edit block tab to edit. Drag layers to reorder, or use the copy and delete controls.</li><li><strong>Take it to Sitecore.</strong> Preview your article, export the HTML, and paste it into your Sitecore HTML field.</li></ol><p>Use public image URLs from your approved media library. Drafts save on this device in this browser. Download HTML for a separate copy. Shared accounts, approvals, and direct Sitecore publishing are not connected in this version.</p>`);}
$('#guideBtn').onclick=guide;$('#helpBtn').onclick=guide;$('#editorNav').onclick=()=>$('#modal').close();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#blocksTab').click();$('#search').focus();}});library();update();
