if(require('node:fs').existsSync('.env'))process.loadEnvFile('.env');
(async()=>{
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const root=__dirname,dataDir=process.env.STUDIO_DATA_DIR||path.join(root,'data');fs.mkdirSync(dataDir,{recursive:true});
const db=process.env.STUDIO_STORAGE==='supabase'?require('./supabase-store').createSupabaseStore({url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SECRET_KEY}):new DatabaseSync(path.join(dataDir,'studio.sqlite'));db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE,password TEXT,role TEXT,reset INTEGER,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER);CREATE TABLE IF NOT EXISTS pages(id TEXT PRIMARY KEY,owner TEXT,title TEXT,blocks TEXT,updated TEXT,shared_by TEXT);`);
function hash(password){const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(password,salt,64).toString('hex');}
function verify(password,encoded){const [salt,key]=encoded.split(':');return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(password,salt,64));}
if(!(await db.prepare('SELECT id FROM users LIMIT 1').get())){const password=process.env.STUDIO_ADMIN_PASSWORD||crypto.randomBytes(15).toString('base64url');await db.prepare('INSERT INTO users VALUES(?,?,?,?,?,1)').run(crypto.randomUUID(),'admin',hash(password),'admin',1);fs.writeFileSync(path.join(dataDir,'initial-admin.txt'),'Username: admin\nTemporary password: '+password+'\nChange this password on first sign-in.\n');console.log('Initial admin credentials saved in data/initial-admin.txt');}
const failures=new Map();const publicUser=u=>({id:u.id,username:u.username,role:u.role,mustChangePassword:!!u.reset});
function reply(res,status,value){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));}
async function body(req){let value='';for await(const chunk of req){value+=chunk;if(Buffer.byteLength(value)>6*1024*1024)throw Error('Request too large');}return value?JSON.parse(value):{};}
function validatePage(b){if(typeof b.title!=='string'||b.title.length>300||!Array.isArray(b.blocks))throw Error('Invalid page');let n=0;const allowed=new Set(['heading','text','columns','image','quote','list','callout','button','divider']);function walk(list,depth){if(depth>8)throw Error('Too many nested columns');for(const b of list){if(++n>500||!b||!allowed.has(b.type)||typeof b.id!=='string')throw Error('Invalid page element');if(b.type==='columns'){if(!Array.isArray(b.columns)||b.columns.length!==2||!b.columns.every(Array.isArray))throw Error('Invalid columns');b.columns.forEach(c=>walk(c,depth+1));}}}walk(b.blocks,0);}
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost'),route=url.pathname;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');
 if(route.startsWith('/api/')){
 if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return reply(res,403,{error:'Invalid request origin'});if(!(req.headers['content-type']||'').startsWith('application/json'))return reply(res,415,{error:'JSON required'});}
 const cookie=(req.headers.cookie||'').match(/(?:^|; )studio_session=([^;]+)/)?.[1];const token=cookie?crypto.createHash('sha256').update(cookie).digest('hex'):'';const user=await db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1').get(token,Date.now());
 if(route==='/api/login'&&req.method==='POST'){const key=req.socket.remoteAddress;const fail=failures.get(key);if(fail&&fail.count>=10&&fail.until>Date.now())return reply(res,429,{error:'Too many attempts. Try again in 15 minutes.'});const b=await body(req);if(typeof b.username!=='string'||typeof b.password!=='string'||b.password.length>256)return reply(res,400,{error:'Invalid credentials'});const u=await db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(b.username.toLowerCase().trim());if(!u||!verify(b.password,u.password)){failures.set(key,{count:(fail?.until>Date.now()?fail.count:0)+1,until:Date.now()+900000});return reply(res,401,{error:'Incorrect username or password'});}failures.delete(key);const raw=crypto.randomBytes(32).toString('hex');await db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(crypto.createHash('sha256').update(raw).digest('hex'),u.id,Date.now()+43200000);res.setHeader('Set-Cookie','studio_session='+raw+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200'+(process.env.STUDIO_SECURE_COOKIE==='1'?'; Secure':''));return reply(res,200,publicUser(u));}
 if(!user)return reply(res,401,{error:'Please sign in'});
 if(route==='/api/me')return reply(res,200,publicUser(user));
 if(route==='/api/logout'&&req.method==='POST'){await db.prepare('DELETE FROM sessions WHERE token=?').run(token);res.setHeader('Set-Cookie','studio_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return reply(res,200,{ok:true});}
 if(route==='/api/password'&&req.method==='POST'){const b=await body(req);if(typeof b.current!=='string'||!verify(b.current,user.password))return reply(res,400,{error:'Current password is incorrect'});if(typeof b.password!=='string'||b.password.length<12||b.password.length>256)return reply(res,400,{error:'Use a password of 12–256 characters'});await db.prepare('UPDATE users SET password=?,reset=0 WHERE id=?').run(hash(b.password),user.id);await db.prepare('DELETE FROM sessions WHERE user_id=? AND token<>?').run(user.id,token);if(user.username==='admin'){const file=path.join(dataDir,'initial-admin.txt');if(fs.existsSync(file))fs.unlinkSync(file);}return reply(res,200,{ok:true});}
 if(user.reset)return reply(res,403,{error:'Change your temporary password first'});
 if(route==='/api/users'&&req.method==='GET')return reply(res,200,await db.prepare('SELECT id,username,role,active FROM users WHERE active=1 ORDER BY username').all());
 if(route==='/api/users'&&req.method==='POST'){if(user.role!=='admin')return reply(res,403,{error:'Administrators only'});const b=await body(req);if(!/^[a-z0-9._-]{3,40}$/.test(b.username||''))return reply(res,400,{error:'Use 3–40 lowercase letters, numbers, dots, dashes or underscores'});const password=crypto.randomBytes(15).toString('base64url');try{await db.prepare('INSERT INTO users VALUES(?,?,?,?,1,1)').run(crypto.randomUUID(),b.username,hash(password),b.role==='admin'?'admin':'editor');}catch{return reply(res,409,{error:'Username already exists'});}return reply(res,201,{username:b.username,temporaryPassword:password});}
 if(route==='/api/pages'&&req.method==='GET')return reply(res,200,(await db.prepare('SELECT * FROM pages WHERE owner=? ORDER BY updated DESC').all(user.id)).map(p=>({id:p.id,title:p.title,blocks:JSON.parse(p.blocks),updated:p.updated,sharedBy:p.shared_by})));
 const match=route.match(/^\/api\/pages\/([a-zA-Z0-9-]+)(\/share)?$/);
 if(match){const id=match[1];const existing=await db.prepare('SELECT * FROM pages WHERE id=?').get(id);if(existing&&existing.owner!==user.id)return reply(res,404,{error:'Page not found'});
 if(!match[2]&&req.method==='DELETE'){if(!existing)return reply(res,404,{error:'Page not found'});await db.prepare('DELETE FROM pages WHERE id=? AND owner=?').run(id,user.id);return reply(res,200,{ok:true});}
 if(!match[2]&&req.method==='PUT'){const b=await body(req);validatePage(b);await db.prepare('INSERT INTO pages(id,owner,title,blocks,updated) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,blocks=excluded.blocks,updated=excluded.updated').run(id,user.id,b.title,JSON.stringify(b.blocks),new Date().toISOString());return reply(res,200,{ok:true});}
 if(match[2]&&req.method==='POST'&&existing){const b=await body(req);const recipient=await db.prepare('SELECT id FROM users WHERE id=? AND active=1').get(b.userId);if(!recipient||recipient.id===user.id)return reply(res,400,{error:'Choose another team member'});const copy=crypto.randomUUID();await db.prepare('INSERT INTO pages VALUES(?,?,?,?,?,?)').run(copy,recipient.id,existing.title,existing.blocks,new Date().toISOString(),user.username);return reply(res,201,{ok:true});}}
 return reply(res,404,{error:'Not found'});
 }
 const allowed=new Set(['/','/index.html','/style.css','/app.js','/account.js','/assets/logos/akkodis-logo-positive.svg']);if(!allowed.has(route)){res.writeHead(404);return res.end('Not found');}const file=path.join(root,route==='/'?'index.html':route);res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'})[path.extname(file)]);res.setHeader('Cache-Control','no-cache');res.end(fs.readFileSync(file));
 }catch(error){reply(res,400,{error:error.message||'Request failed'});}});
server.listen(Number(process.env.PORT)||3000,process.env.HOST||'127.0.0.1',()=>console.log('Blog Studio: http://localhost:'+(process.env.PORT||3000)));

})().catch(error=>{console.error(error.message);process.exitCode=1;});
